


get http://localhost:3000/historial/user/67784a9308be13c7d8ae3956

###

GET http://localhost:3000/prestamo_by_id/6764980256e075634be2e6b7


###
GET http://localhost:3000/prestamo_by_id/6780425ec750877e2e78e9ad

###

GET http://localhost:3000/usuarios/clientes/677ed60b31afa8b38d16303c


###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nombre": "Savannah",
    "email": "savannahsueyong.gmail.com",
    "password": "123A&A",
    "role": "CLIENTE",
    "saldo_asignado": 10000,
    "telefono": 4961368965,
    "direccion": "NA",
    "created_by": "6463debc096500b73df445b5",
    "assigned_to":"6463e9fb20a73c4bfb7c5483"
}

###
POST http://localhost:8382/wallet/iniciar-wallet
Content-Type: application/json

{
    "owner": "688da59bfb293ae6030bc09f",
    "saldoInicial": 24000,
}


###
POST http://localhost:8382/prestamo
Content-Type: application/json

{
    "saldo": 2000,
    "periodo": 14,
    "id_asesor": "68aab15fded423d919fb3b46",
    "id_cliente": "69029ca57fa4dba77d33d1fd",
    "dia_pago": "Lunes",
}